In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv("/Users/sami/Documents/CS Postgrad/IDS/COIY065D7_Anomaly-Based-IDS/Data/cleaned_dataset.csv")

In [3]:
X = df.drop(columns = ["attack_type", "binary_label"])
Y = df["binary_label"]

In [4]:
print("X =", X.shape)
print("Y =", Y.shape)
X.head()

X = (21693978, 39)
Y = (21693978,)

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
0,8.0,17,64.00,27800.782130,0.00,0.00,0.0,0.0,0.00,0.0,...,1.0,16200.0,162.0,162.0,162.00,0.000000,162.00,0.000036,100.0,0.000000
1,8.0,17,64.00,22451.043785,0.00,0.00,0.0,0.0,0.00,0.0,...,1.0,16200.0,162.0,162.0,162.00,0.000000,162.00,0.000045,100.0,0.000000
2,8.0,17,65.91,4002.885992,0.00,0.00,0.0,0.0,0.00,0.0,...,1.0,16268.0,162.0,230.0,162.68,6.800000,162.68,0.000250,100.0,46.240000
3,8.0,17,64.00,7530.709566,0.00,0.00,0.0,0.0,0.00,0.0,...,1.0,16200.0,162.0,162.0,162.00,0.000000,162.00,0.000133,100.0,0.000000
4,8.8,17,65.91,4367.383404,0.01,0.01,0.0,0.0,0.02,0.0,...,1.0,15896.0,66.0,230.0,158.96,19.679205,158.96,0.000229,100.0,387.271111

In [5]:
x_train_KNN, x_temp_KNN, y_train_KNN, y_temp_KNN = train_test_split(X, Y, test_size = 0.2, random_state = 42, stratify = Y)

In [7]:
x_val_KNN, x_test_KNN, y_val_KNN, y_test_KNN = train_test_split(x_temp_KNN, y_temp_KNN, test_size = 0.5, random_state = 42, stratify = y_temp_KNN)

In [8]:
print("KNN Training split:", "x_train_KNN =", x_train_KNN.shape, "y_train_KNN =", y_train_KNN.shape)
print("KNN Validation split:", "x_val_KNN =", x_val_KNN.shape, "y_val_KNN =", y_val_KNN.shape)
print("KNN Testing split:", "x_test_KNN =", x_test_KNN.shape, "y_test_KNN =", y_test_KNN.shape)

KNN Training split: x_train_KNN = (17355182, 39) y_train_KNN = (17355182,)
KNN Validation split: x_val_KNN = (2169398, 39) y_val_KNN = (2169398,)
KNN Testing split: x_test_KNN = (2169398, 39) y_test_KNN = (2169398,)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [16]:
x_test = pd.read_csv("/Users/sami/Documents/CS Postgrad/IDS/COIY065D7_Anomaly-Based-IDS/Data/x_test.csv")

In [17]:
x_train_scale = scaler.fit_transform(x_train_KNN)
x_val_scale = scaler.transform(x_val_KNN)
x_test_scale = scaler.transform(x_test)

In [18]:
print(x_train_scale.shape)
print(x_val_scale.shape)
print(x_test_scale.shape)

(17355182, 39)
(2169398, 39)
(218776, 39)

In [21]:
print("Before scaling:") 
x_train_KNN.head()

Before scaling:

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
9352760,20.00,6,64.00,121785.830430,0.00,0.23,0.77,0.00,0.00,0.0,...,1.0,6000.0,60.0,60.0,60.00,0.000000,60.00,0.000008,100.0,0.000000
18982803,19.80,6,63.37,6597.618486,0.00,0.00,0.00,0.00,0.00,0.0,...,1.0,6000.0,60.0,60.0,60.00,0.000000,60.00,0.000152,100.0,0.000000
15372966,16.80,17,107.20,65.910039,0.00,0.20,0.00,0.00,0.20,0.0,...,1.0,1604.0,66.0,330.0,160.40,118.906312,160.40,0.019046,10.0,14138.711111
15435750,25.60,6,60.00,200.846809,0.20,0.10,0.00,0.20,0.60,0.0,...,1.0,1046.0,60.0,441.0,104.60,118.320844,104.60,0.004979,10.0,13999.822222
411068,7.92,17,82.67,4423.997975,0.01,0.00,0.00,0.01,0.03,0.0,...,1.0,6493.0,60.0,441.0,64.93,38.112342,64.93,0.000226,100.0,1452.550606

In [24]:
x_train_scale = pd.DataFrame(x_train_scale, columns = x_train_KNN.columns)
print("After scaling:")
x_train_scale[:5]

After scaling:

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,LLC,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance
0,0.651370,-0.452421,-0.261418,3.301799,-0.263716,0.087480,2.827484,-0.361670,-0.503333,-0.020533,...,0.21078,-0.436948,-0.253079,-0.424419,-0.470615,-0.347163,-0.470615,-0.000754,0.345283,-0.129903
1,0.629406,-0.452421,-0.291799,-0.406307,-0.263716,-0.509017,-0.302823,-0.361670,-0.503333,-0.020533,...,0.21078,-0.436948,-0.253079,-0.424419,-0.470615,-0.347163,-0.470615,-0.000750,0.345283,-0.129903
2,0.299955,0.503293,1.821843,-0.616574,-0.263716,0.009676,-0.302823,-0.361670,0.090053,-0.020533,...,0.21078,-0.625953,-0.212622,-0.094329,-0.153273,0.115339,-0.153273,-0.000201,-2.907929,-0.105105
3,1.266345,-0.452421,-0.454313,-0.612230,0.586467,-0.249670,-0.302823,0.410607,1.276823,-0.020533,...,0.21078,-0.649944,-0.253079,0.041374,-0.329644,0.113061,-0.329644,-0.000610,-2.907929,-0.105348
4,-0.675220,0.503293,0.638917,-0.476280,-0.221207,-0.509017,-0.302823,-0.323056,-0.414325,-0.020533,...,0.21078,-0.415751,-0.253079,0.041374,-0.455032,-0.198920,-0.455032,-0.000748,0.345283,-0.127355

In [29]:
x_train_KNN_sample, _, y_train_KNN_sample, _ = train_test_split(x_train_scale, y_train_KNN, train_size  = 100000, stratify = y_train_KNN)

In [36]:
print("x_train_KNN_sample shape:", x_train_KNN_sample.shape)
print("y_train_KNN_sample shape:", y_train_KNN_sample.shape)

x_train_KNN_sample shape: (100000, 39)
y_train_KNN_sample shape: (100000,)